# Generated by Django 5.1.1 on 2024-11-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklotkov', '0005_alter_balancerequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_repaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('credit', 'Credit'), ('tax', 'Tax'), ('fine', 'Fine'), ('loan', 'Loan Disbursement'), ('repayment', 'Loan Repayment')], max_length=10),
        ),
    ]
