# Generated by Django 5.1.7 on 2025-03-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklotkov', '0007_profile_avatar_profile_birth_date_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('transfer', 'Transfer'), ('credit', 'Credit'), ('tax', 'Tax'), ('fine', 'Fine'), ('loan', 'Loan Disbursement'), ('repayment', 'Loan Repayment')], max_length=10),
        ),
    ]
